### ISSUE TITLE
Extension works fine in Firefox but have scrolling issue

### ISSUE THREAD

**Issue by amazingpaddy** [anaclumos/bing-chat-for-all-browsers#1]
I am able to access bing chat in firefox, but I couldnt scroll up to see my previous conversations. Can you please take a look.

**Comment by anaclumos** [comment]
I confirmed this problem is happening. Will investigate it soon.

**Comment by rany2** [comment]
Solution is simple, just set `layout.css.overflow-overlay.enabled` to true in about:config.

**Comment by rany2** [comment]
@amazingpaddy definitely working for me, probably you need to be on the beta (it works for me on developer edition)

**Comment by rany2** [comment]
Actually it does work with `layout.css.overflow-overlay.enabled` set to true on Firefox Stable (version 110.0) as well.

**Comment by amazingpaddy** [comment]
Yes I confirm now its worked after **I updated my version to 110.0**, earlier I was using Firefox version 109 and it didnt work..

**Comment by rany2** [comment]
@amazingpaddy Could you keep this open? I think this extension should set this config for the user (an extension is capable of setting about:config options on the user's behalf)

**Comment by amazingpaddy** [comment]
Sure. Reopened

**Comment by anaclumos** [comment]
> @amazingpaddy Could you keep this open? I think this extension should set this config for the user (an extension is capable of setting about:config options on the user's behalf)

Hey, I've done some research and need help finding a reference to such documentation. On [this website](https://wiki.mozilla.org/WebExtensions/FAQ#Will_I_have_access_to_about:config_or_the_preferences.3F):

- Does the WebExtensions API provide access to preferences?
- No. Direct access to preferences in the past has caused many problems. Multiple extensions would try to change them and conflict, and the lack of security limitations meant malicious extensions could take advantage of users. Instead, WebExtensions focus on higher-level APIs that implement specific tasks.

Can you kindly provide any resources I am missing?

**Comment by rany2** [comment]
@anaclumos Sorry, but I am sure this used to be the case. uBlock Origin used to be able to set prefs.

**Comment by anaclumos** [comment]
Working on it!

**Comment by anaclumos** [comment]
Released v1.0.1. Please take a look!
