### ISSUE TITLE
in Vivaldi. Crashes when clicking on links in the extension

### ISSUE THREAD

**Issue by Mink16** [anaclumos/bing-chat-for-all-browsers#10]
[Vivaldi version](https://vivaldi.com/blog/vivaldi-5-7-on-desktop/) : 5.7.2921.53
Chromium version : 110.0.5481.111

When I restart my browser and open the page, I can view the page without problems.

1. click extension
2. click links in popup
3. Click anywhere on the page displayed.
   1. It occurs on all links.

**Comment by anaclumos** [comment]
Confirmed, working on a fix now

**Comment by anaclumos** [comment]
Can you check if this build https://github.com/anaclumos/bing-chat-for-all-browsers/blob/new-tab-fix/release/chrome.zip resolves the problem?

**Comment by anaclumos** [comment]
v1.0.4 was released with this change. Please let me know if the issue persists.

**Comment by Mink16** [comment]
Oh. Sorry I didn't notice your comment.
I just tried it in my own browser and can confirm the problem is fixed! Thanks so much. 👍
