### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by rbansal42** [anaclumos/bing-chat-for-all-browsers#100]
The extension stopped working for me on Arc Browser. Probably has something to do with the new features Bing pushed out recently.
When I search, even normal bing search fails.
<img width="896" alt="image" src="https://github.com/anaclumos/bing-chat-for-all-browsers/assets/50016724/10e455b9-f0f0-4539-94fd-73ee66ae7273">

Update: Already tried clearing cache, cookies, logging out and in

**Comment by Mrgaton** [comment]
yup

**Comment by lectrichead** [comment]
Having same version with the Chrome extension in Brave - keeps prompting to open in Edge.

**Comment by TannerDunning** [comment]
> Having same or similar problem with the version of the Chrome extension in Brave - keeps prompting to open in Edge.

Same. Using brave here too

**Comment by rizkidewanto** [comment]
![image](https://github.com/anaclumos/bing-chat-for-all-browsers/assets/46876786/766670cd-37e2-425d-a796-9ca67342f480)
Same. Using chrome extension on opera

**Comment by anaclumos** [comment]
> ![image](https://user-images.githubusercontent.com/46876786/238851373-766670cd-37e2-425d-a796-9ca67342f480.png) Same. Using chrome extension on opera

opera — see #2 and #93

**Comment by anaclumos** [comment]
For other browsers. I am baffled about what's going on 😭 It's just so hard when things work non-deterministically. Sometimes it just works, but sometimes it will never work whatever I do. Any help will be heavily appricieated.

**Comment by rbansal42** [comment]
Hey, so I didn't do anything really, and found that the extension was working again.

I think it had something to do with the recent updates that were pushed out to Bing Chat. The features were in a state of flux then. Clearly experimental.
They seem to be working consistently now. Could that be the cause of the issue?

**Comment by anaclumos** [comment]
Thank you for clarifying! It seems like Microsoft may still be working on resolving the issue. I'm unsure how to determine if the problem is caused by Microsoft or myself in these cases 😭

**Comment by rbansal42** [comment]
Maybe you can add in some sort of analytics to determine? Like, maybe the extension can report when it works and when it doesn't work. This way, you would have data on when a fault is occurring, and it can be corresponded with news on MS pushing some updates.

**Comment by lectrichead** [comment]
It started working again for me in Brave again.

**Comment by Zabooby** [comment]
Working again in Firefox.

**Comment by Mrgaton** [comment]
For me it works on one pc and in another don't

**Comment by PleahMaCaka** [comment]
I keep getting a message use Edge, if I reinstalling the extension fixes this for a while, but than again - in Brave

**Comment by sup2069** [comment]
> I keep getting a message use Edge, if I reinstalling the extension fixes this for a while, but than again - in Brave

Having the same issue with Brave Nightly v1.53.54 / Linux. Worked up to about a week ago.

**Comment by PleahMaCaka** [comment]
[ ✔️ ] Chrome 113.0.5672.127
 [ ✔️ ] Brave Latest 1.51.118 (Chromium 113.0.5672.126) 
 [ ❌ ] Brave Nightly 1.54.9 (Chromium 114.0.5735.53)
Once after installation this extension works, but when I close the tab and try again, it doesn't work in Brave Nightly.

**Comment by PleahMaCaka** [comment]
#104

**Comment by PleahMaCaka** [comment]
> > I keep getting a message use Edge, if I reinstalling the extension fixes this for a while, but than again - in Brave
> 
> Having the same issue with Brave Nightly v1.53.54 / Linux. Worked up to about a week ago.

I think is difference topic #104

**Comment by LuisAPI** [comment]
Stopped working in Firefox 113.0.2 / Windows 11 64-bit too

![Screenshot of the Bing search for "Bing AI", which bing.com/chat now redirects me to](https://github.com/anaclumos/bing-chat-for-all-browsers/assets/7901433/f71df947-4fb8-4cc7-a55a-2fa99ca02c49)

**Comment by anaclumos** [comment]
#119
