### ISSUE TITLE
chromeの拡張機能bing chat の使い勝手の感想

### ISSUE THREAD

**Issue by takuyatahata** [anaclumos/bing-chat-for-all-browsers#101]
Hi, @anaclumos
今日インストールして使ってみましたが、結局Edge以外のほかのブラウザから起動するのではなく、Edgeに飛んでから使えるようになります。microsoftのアカウントがあれば、openaiの方のアカウントが無くても使えます。
日本語で書きました。
改善したい場合、製作者に連絡を取る方法はありますか？

**Comment by anaclumos** [comment]
You are talking to the creator 😄 I am the creator.

Please head over to https://github.com/anaclumos/bing-chat-for-all-browsers/blob/main/uninstall.md for instructions.

**Comment by takuyatahata** [comment]
@anaclumos 
May we discuss it here?
I would like to save the contents of the exchange on edge, but it seems that I cannot save the logs without an openai account.

**Comment by anaclumos** [comment]
#119
