### ISSUE TITLE
Heavy lag on Firefox

### ISSUE THREAD

**Issue by phly95** [anaclumos/bing-chat-for-all-browsers#103]
When trying to use Bing with the extension on Firefox, the Bing page freezes for a few seconds before you can use the page.

**Comment by anaclumos** [comment]
Do you feel faster on Chrome or Edge? It might be Bing simply not optimized.

**Comment by phly95** [comment]
Looks like it's just Firefox. Chrome is still fast. Firefox without Bing chat still works fine.

**Comment by anaclumos** [comment]
#119
