### ISSUE TITLE
我问一个很基础的问题：area区域换来换去还是china

### ISSUE THREAD

**Issue by zhl111** [anaclumos/bing-chat-for-all-browsers#105]
必须vpn换成全局的吗？似乎有的vpn换成全局的也不好使呢？
何解？

**Comment by thlz998** [comment]
试试这个看？挺好用的，挺方便
https://chrome.google.com/webstore/detail/new-bing-anywhere/hceobhjokpdbogjkplmfjeomkeckkngi

**Comment by halfu** [comment]
应该是你的DNS分流或者路由分流有问题，与插件无关。
We should use English here.
I think this has nothing to do with the browser extension. It's just that your DNS problem has redirected you to bing.cn.

**Comment by anaclumos** [comment]
#119
