### ISSUE TITLE
2023-06-01 Stopped working again

### ISSUE THREAD

**Issue by huyz** [anaclumos/bing-chat-for-all-browsers#108]
It was working fine for weeks, but it stopped working today.

**Comment by Cedar3702** [comment]
Yeah, it recently stopped working for me too. Do you think they realized that their lock could be bypassed?

**Comment by 686D7A** [comment]
Not working to me as well
02.06

**Comment by Luisdar0z** [comment]
Not working

**Comment by vpsone** [comment]
Try to reinstall the extension , it worked for me.

**Comment by Cedar3702** [comment]
Yeah I did that and that didn't work for me

**Comment by SethuSenthil** [comment]
Re-installing the extension worked for me. I'll try to investigate why this is occurring.
