### ISSUE TITLE
Not working on Brave

### ISSUE THREAD

**Issue by CristianArean** [anaclumos/bing-chat-for-all-browsers#109]
It seems like if you want to use it on any other browser than Chrome you'll have troubles

**Comment by alescdb** [comment]
Same for me, it used to work fine, but now Bing asks me to download Edge again...
Don't know if it is specific to Brave or not.
(I'm on Linux, if it changes something, and my locale on Brave is fr_FR)

**Comment by CristianArean** [comment]
> Same for me, it used to work fine, but now Bing asks me to download Edge again... Don't know if it is specific to Brave or not. (I'm on Linux, if it changes something, and my locale on Brave is fr_FR)

yes, I'm using Linux too. Could be that the problem? I don't know in deep how extensions work on chromium-based browsers.

**Comment by alescdb** [comment]
> > Same for me, it used to work fine, but now Bing asks me to download Edge again... Don't know if it is specific to Brave or not. (I'm on Linux, if it changes something, and my locale on Brave is fr_FR)
> 
> yes, I'm using Linux too. Could be that the problem? I don't know in deep how extensions work on chromium-based browsers.

Just tried on Brave on Windows and it still works, so it seems to be a Linux issue...

**Comment by alescdb** [comment]
It seems Bing Chat is coming on non Edge browser anyway...
https://twitter.com/MParakhin/status/1665390126443245572

**Comment by raymen1** [comment]
I am using this on windows (also Brave) and the message appeared recently, not only a linux issue.

**Comment by tatejuan12** [comment]
I'm using Brave on a Arch Linux. Had the same issue arise just now. Uninstalled and installing the extension fixed the issue. Hopefully it works for you too!

**Comment by Posandu** [comment]
Brave user on Windows here, reinstalling the extension worked for me.

**Comment by cowwoc** [comment]
There is no need to reinstall the extension. All you need to do is disable and re-enable it. I reloaded the Bing page in between the two steps, but I don't think that's necessary.

**Comment by CristianArean** [comment]
well it seems that reinstalling works. Thaks to you all!

**Comment by cowwoc** [comment]
I don't think that this issue should be closed. The problems keeps on happening every couple of days. Yes, we have a workaround but it would be great to have a permanent fix.

**Comment by raymen1** [comment]
Was about to comment the same as @cowwoc , even after reinstalling it happened again after a day or so ~~.

**Comment by alescdb** [comment]
It seems the user-agent used for firefox in working for all (tried in a unpacked version), why not use it for all browsers (and maybe ditch the mobile support to simplify)  ?
