### ISSUE TITLE
Not working on Brave Browser

### ISSUE THREAD

**Issue by FoxBazo** [anaclumos/bing-chat-for-all-browsers#113]
I have checked the five conditions:

1. Login with a MS account on BING --> OK
2. Disable VPN -->OK
3. Clear cache --> OK
4. Disable AdBlocker on bing --> OK (disable the built-in adblocker of Brave)
5. Delete Bing cookie --> Not OK, you cannot remove a cookie when the Brave AdBlock is disabled; if I re-enable the Brave AdBlocker then I can remove the cookie but obviously... an AdBlocker is enabled !
When you click on the extension account then on Open Bing Chat, it simply displays the pop-up to open Bing Chat in Edge...

**Comment by marleymwangi** [comment]
Having the same issue

**Comment by drunkskeletor** [comment]
Still not working on Brave Browser.

**Comment by marleymwangi** [comment]
> Having the same issue

Its now resolved. Thanks for the good work

**Comment by FoxBazo** [comment]
Yeap, I agree, it's been fixed since a few days. Thanks for the good work.

**Comment by FoxBazo** [comment]
This issue is fixed.
Here are the way to make it work:
1. Login with a MS account on BING
2. Disable VPN
3. Clear Brave Cache
4. Disable Brave Shields on the Bing page (= disable the built-in adblocker of Brave)
5. Disable any third party ad-blocker that you might have installed through an extension
6. Only use the button "Open Bing Chat of the extension, do not try to use a favourite/bookmark for the Bing Chat page in Brave
Thanks to the developer.
