### ISSUE TITLE
Not working on Brave (sometimes)

### ISSUE THREAD

**Issue by Samueru-sama** [anaclumos/bing-chat-for-all-browsers#117]
If I install on brave browser it does work, but if I close the browser, open it again and open bing it doesn't work.

I have to go to the extension, disable and enable it for it to work again, reinstalling also works.

**Comment by anaclumos** [comment]
@113

**Comment by Samueru-sama** [comment]
> #113

Tried everything listed in there, didn't work.

https://imgur.com/a/MnDrQ89

But if I disable and enable the extension, it gets fixed.

**Comment by TCMAD** [comment]
Same issue here.

**Comment by j4k0xb** [comment]
could someone debug/explain *why* an extension that only edits the user agent breaks from time to time, but starts working again when reinstalling?

**Comment by TCMAD** [comment]
You're right @j4k0xb, I wasn't able to access to bing AI and after reinstall the plugin, I can use it now!

**Comment by Samueru-sama** [comment]
> could someone debug/explain _why_ an extension that only edits the user agent breaks from time to time, but starts working again when reinstalling?

You can also disable and enable the extension instead of reinstalling and it should work again, but yeah that's a band-aid fix.

**Comment by anaclumos** [comment]
#119
