### ISSUE TITLE
Chrome plugin problem

### ISSUE THREAD

**Issue by ivostoykov** [anaclumos/bing-chat-for-all-browsers#118]
The only action this can do on Chrome is to offer me to download Edge! Although I can understand the marketing strategy, this behaviour is very annoying from the user's perspective.
![Screenshot from 2023-06-29 21-24-51](https://github.com/anaclumos/bing-chat-for-all-browsers/assets/889184/b352dcab-4b71-4fef-aa21-ba1ceefa7c6b)

**Comment by anaclumos** [comment]
#119
