### ISSUE TITLE
Scrolling does not work on Firefox

### ISSUE THREAD

**Issue by LinusKromnow** [anaclumos/bing-chat-for-all-browsers#13]
As the title says: Scrolling does not work on Firefox.

**Comment by anaclumos** [comment]
Hi, can you confirm if you enabled `layout.css.overflow-overlay.enabled` in `about:config`? #1

**Comment by anaclumos** [comment]
+ Can you confirm if you updated to the latest Firefox version,

If the issue persists after doing both, let me know.

**Comment by LinusKromnow** [comment]
I did not have it enabled and Firefox is updated.
With layout.css.overflow-overlay.enabled enabled it now works.
