### ISSUE TITLE
[Request] Dark Mode?

### ISSUE THREAD

**Issue by callbacked** [anaclumos/bing-chat-for-all-browsers#15]
All of the universal dark mode extensions that I've used do not work at all, turns out its due to the background being a blinding white image. Could it be possible to add a toggle that swaps the stock image for a dark one or some dark color?

![image](https://user-images.githubusercontent.com/117959902/220813682-cf950f91-564c-4b55-9a59-4bbc76b36d5f.png)

**Comment by anaclumos** [comment]
Sure, I'll try to see if I can do anything with this. Thank you for the suggestion and for analyzing where I should start.

**Comment by wrinkledeth** [comment]
I second that this would be an awesome feature.

**Comment by NotAF0e** [comment]
Yep same here. Using *chrome://flags* and dark mode with selective image inversion looks horrible on it:
![image](https://user-images.githubusercontent.com/75176016/222903700-b4f49c6a-d737-4953-b592-933f210fa4cb.png)

**Comment by anaclumos** [comment]
Hey everyone,

Thank you for raising this issue. I completely understand the pain point you are facing. I am currently swamped with midterms, so unfortunately, I won't be able to work on it right now. However, I'd like to encourage anyone interested to contribute. Your help would be greatly appreciated.

Thanks again for bringing this to my attention.

**Comment by callbacked** [comment]
As someone who is also swamped with midterms, I completely understand. I wish you the best of luck with them!

Unfortunately, I don't know anything about .js so I'm of no use. :(

**Comment by wrinkledeth** [comment]
best of luck on the midterms :)

**Comment by wrinkledeth** [comment]
That's a good solution Tedd, thanks

**Comment by ArjixWasTaken** [comment]
you are kidding, no way, they are using a white image for the background? wow
a 2 trillion company cant use CSS gradients for the background

**Comment by Ouskit** [comment]
This works perfect for me, you can try this Tampermonkey script.
[Bing Chat Dark Mode](https://greasyfork.org/en/scripts/462516-bing-chat-dark-mode)

**Comment by JohnGarnerIII** [comment]
Thanks again Tedd, filter+ does indeed work but the text is blurry. Will use it in the meantime though.
![Screenshot 2023-04-09 064447](https://user-images.githubusercontent.com/66663652/230768160-8d5c7ce5-6819-44bf-a3df-4c182dbcddbf.png)

**Comment by Johnnycyan** [comment]
I created this Stylus theme to fix Bing Chat to work with dark mode extensions https://userstyles.world/style/9586/bing-chat-fix-dark-reader

**Comment by Boreo** [comment]
https://github.com/darkreader/darkreader/issues/10784

Has fixes for Dark Reader.
