### ISSUE TITLE
Shift+Return does not create a line break

### ISSUE THREAD

**Issue by JustYourBud** [anaclumos/bing-chat-for-all-browsers#16]
I've only tried this extension on Firefox but when using shift+return to try and create a line break in a message, it stays on the same line.
I have my settings set to the recommended ones in the README, so I'm not sure where this issue is coming from. It's not a huge one but it makes sending something like a block of code relativity more difficult.

**Images from Firefox and Edge respectively**
![image](https://user-images.githubusercontent.com/59189197/221106135-26e2b022-b461-468a-a319-feb312d03c73.png)
![image](https://user-images.githubusercontent.com/59189197/221106071-70926db3-29d4-48e6-aaab-933723dd41f9.png)

**Comment by anaclumos** [comment]
I'll try to look into this. One question: Doesn't Bing eventually ignore all line breaks when submitting the prompt?

**Comment by JustYourBud** [comment]
I'm not sure, I haven't been able to use it enough. The only scenario I could see where you'd want to use them a lot is, like I said, writing a quick snippet of code or something.
![image](https://user-images.githubusercontent.com/59189197/221329022-0ca87a5a-84cb-4a5b-97a9-849d52540f73.png)

**Comment by JustYourBud** [comment]
So after using it a bit more, the formatting does get lost once you send your message (or at the very least the code I sent was completely jumbled), thought I don't think Sydney seems to care--she still understands perfectly.

I do still think it would be a good thing to have, just for the sake of making sure everything is properly formatted in the input box beforehand, regardless of how the output displays. Personally speaking it just helps me make sure everything is correct before I send it to Bing, which is especially important right now when conversations are still so limited.

**Comment by anaclumos** [comment]
Ok. I'll look into the matter.

**Comment by DovieW** [comment]
It seems to be working fine for me.

**Comment by fullerenedream** [comment]
I have this problem too. It's hard to read my own messages without being able to use line breaks.

**Comment by archont00** [comment]
The biggest issue is when I try to type (or even paste from plain text editor) a code block. It is pretty tough to read code without visible line breaks :-) On the other hand, it seems that line break characters are preserved as Bing happily translates the code to other programming language without errors. (I use Firefox, Ubuntu Linux.)

**Comment by JustYourBud** [comment]
I think it's worth noting that Bing has recently been updated to render line breaks in the user's message bubbles now, despite Firefox still not displaying it properly. Doesn't really help with this issue in particular but I thought it was worth a mention that they are registered during _and_ after being sent, even though not shown in the input box.

<img width="762" alt="Screenshot 2023-05-11 at 12 29 57 AM" src="https://github.com/anaclumos/bing-chat-for-all-browsers/assets/59189197/322250e6-4c9b-4d5a-a127-c2cc38c00097">

**Comment by anaclumos** [comment]
I think the message-composing area is crucial. However, the current Bing design employs a `label`, which makes it impossible to create a line break. Can you suggest any alternatives?

**Comment by jcuenod** [comment]
```
document.querySelector("cib-serp")
    .shadowRoot.querySelector("cib-action-bar")
    .shadowRoot.querySelector("#searchboxform label")
        .style.whiteSpace = "pre-wrap"
```

**Comment by anaclumos** [comment]
#119
