### ISSUE TITLE
Does not work in Brave

### ISSUE THREAD

**Issue by TheMG95** [anaclumos/bing-chat-for-all-browsers#18]
It gives this error when I try to send a message.
<img width="411" alt="image" src="https://user-images.githubusercontent.com/66237187/221539924-97a75807-546f-47c0-9458-a6c873d13987.png">

**Comment by anaclumos** [comment]
Hi, that may be Bing's error. I have also had that message on Edge, probably when Bing is experiencing a high amount of traffic.

**Comment by anaclumos** [comment]
Please feel free to reopen the issue if the issue persists.

**Comment by TheMG95** [comment]
The issue is still persisting and i get the same error

**Comment by TheMG95** [comment]
I think it may be because this header is not being sent
<img width="332" alt="image" src="https://user-images.githubusercontent.com/66237187/221755157-04a6e63f-114a-4a2d-9311-ac5d99bcba90.png">

**Comment by anaclumos** [comment]
Hmm, okay. From my end, I can access the service. 

<img width="1792" alt="Screenshot 2023-02-27 at 9 57 43 PM" src="https://user-images.githubusercontent.com/31657298/221767019-5c73eafd-9268-4618-874f-76d5811db3b3.png">

From a user on Chrome Extension Store:

<img width="533" alt="Screenshot 2023-02-27 at 9 51 28 PM" src="https://user-images.githubusercontent.com/31657298/221765961-dfb9f70c-8210-4190-ac2f-c09b3952b2b7.png">

So, it may be possible that this is a local problem. What is your OS version and Brave browser version?

**Comment by TheMG95** [comment]
Im on `Version 1.48.171 Chromium: 110.0.5481.177` in macOS

**Comment by TheMG95** [comment]
I logged out and logged back from Bing and it fixed my issue, I think it was not related to the extension, sorry.

**Comment by FernandoPerezLara** [comment]
Same problem here with Brave 1.48.171 Chromium: 110.0.5481.177.

Maybe the problem is not the extension, but I also report this problem.

**Comment by anaclumos** [comment]
Hi @FernandoPerezLara, glad that logging in helped to resolve the issue. As of right now, Bing requires an MS account. Happy Bing-ing!
