### ISSUE TITLE
Firefox - no scroll 

### ISSUE THREAD

**Issue by netapy** [anaclumos/bing-chat-for-all-browsers#19]
Hi, thanks for this really cool extension ! 
I've noticed the scroll is disabled on the bing chat page when using this extension.

Thanks !

**Comment by anaclumos** [comment]
Hi, did you check if you set `layout.css.overflow-overlay.enabled` to true in about:config, and update to the latest version of Firefox? It should've prompted you on install, maybe I should add a more descriptive instruction.

**Comment by netapy** [comment]
I don't remember seeing that, but it's probably just me.

Thanks !
