### ISSUE TITLE
Not working for Opera

### ISSUE THREAD

**Issue by Saftygo2** [anaclumos/bing-chat-for-all-browsers#2]
Not working for Opera. It's working fine with Chrome and Brave browsers.

**Comment by anaclumos** [comment]
Confirmed the error. Will explore it soon.

**Comment by Saftygo2** [comment]
> Confirmed the error. Will explore it soon.

I can access to the Bing Chat via Opera using the following link: https://edgeservices.bing.com/edgediscover/query?&darkschemeovr=1&FORM=SHORUN&udscs=1&udsnav=1&setlang=en-US&features=udssydinternal&clientscopes=windowheader,coauthor,chat,&udsframed=1
Maybe this will help you fix the error.

**Comment by anaclumos** [comment]
Hey, I have tried investigating this but cannot figure out what's happening. The other extensions that modify the header also do not work for Opera. Extra help from other devs will be highly appreciated!

**Comment by anaclumos** [comment]
[User-Agent-Switching Extensions do not work in Opera? | Opera forums](https://forums.opera.com/topic/43130/user-agent-switching-extensions-do-not-work-in-opera?lang=en-US)

**Comment by NerdyWanKenobi** [comment]
> For those who are okay with switching UA globally: you can start Opera with
> 
> ```
> opera --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.63"
> ```
> 
> because the switches are the same as in Chromium.

How do I change the user agent string?  I have tried following multiple tutorials, including https://forums.opera.com/topic/34771/making-opera-identify-as-another-browser, https://winaero.com/change-user-agent-opera/, https://helpdeskgeek.com/how-to/how-to-change-your-browsers-user-agent-without-installing-an-extension/, and https://www.groovypost.com/howto/change-user-agent-string-edge-chrome-firefox-opera-internet-explorer-safari, and installing the Opera extension: https://addons.opera.com/en/extensions/details/custom-useragent-string/, but none of these methods are working.

**Comment by Saftygo2** [comment]
> > For those who are okay with switching UA globally: you can start Opera with
> > ```
> > opera --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.63"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > because the switches are the same as in Chromium.
> 
> How do I change the user agent string? I have tried following multiple tutorials, including https://forums.opera.com/topic/34771/making-opera-identify-as-another-browser, https://winaero.com/change-user-agent-opera/, https://helpdeskgeek.com/how-to/how-to-change-your-browsers-user-agent-without-installing-an-extension/, and https://www.groovypost.com/howto/change-user-agent-string-edge-chrome-firefox-opera-internet-explorer-safari, and installing the Opera extension: https://addons.opera.com/en/extensions/details/custom-useragent-string/, but none of these methods are working.


Currently there is only one way to switch the user-agent for Opera to access Bing chat via Bing search website. In the Opera program files directory, right-click on launcher.exe to create a new shortcut and place it on your desktop. Then, on the desktop, rename it what you want. Then, right-click on the shortcut, goto properties and then the "shortcut" tab. On that tab, modify the target to add the --user-data-dir command-line switch.

For example:

"C:\Program Files (X86)\Opera\launcher.exe" "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.57"

Save the changes and restart Opera. That's all. 

The second method -  install "bing-chat-for-all-browsers" extension on Opera and you'll get directly access to the Bing chat sidebar application here: https://edgeservices.bing.com/edgediscover/query?&darkschemeovr=1&FORM=SHORUN&udscs=1&udsnav=1&setlang=en-US&features=udssydinternal&clientscopes=windowheader,coauthor,chat,&udsframed=1

**Comment by shani-ace** [comment]
> I can access to the Bing Chat via Opera using the following link: https://edgeservices.bing.com/edgediscover/query?&darkschemeovr=1&FORM=SHORUN&udscs=1&udsnav=1&setlang=en-US&features=udssydinternal&clientscopes=windowheader,coauthor,chat,&udsframed=1 Maybe this will help you fix the error.

> Hey, I have tried investigating this but cannot figure out what's happening.
Wouldn't a simple redirect to that URL above do the trick?

**Comment by mayachhism** [comment]
Has the nproblem solved yet? This above link is not opening.

**Comment by anaclumos** [comment]
Nope, I couldn't find a solution after weeks of debugging sessions. @operasoftware
