### ISSUE TITLE
Chrome - Scrolls down broke the navigation

### ISSUE THREAD

**Issue by Tefery** [anaclumos/bing-chat-for-all-browsers#20]
On Chrome v110.0.5481.178 x64, when in a middle of a conversation with Bing Chat scrolls down, when returning to the conversation (scrolls up), the chat breaks and you need to reload to continue (losing the previous conversation)`

> Uncaught Error: IConversationManager.sendSearchQuery can only be called as the first message of conversation.
>     at bc.sendSearchQuery (L77SImMVlZrSs9W9xFYQle9i4nA.br.js:2:1280684)
>     at CibSerpApi.sendSearchQuery (L77SImMVlZrSs9W9xFYQle9i4nA.br.js:6707:7794)
>     at or (A4oJbKqB-nXnwlRIr1h2zsJrTsY.br.js:1:13158)
>     at fr (A4oJbKqB-nXnwlRIr1h2zsJrTsY.br.js:1:10807)
>     at e (6Hy0l7O248Q6ir-oX_Eoni2EIwg.br.js:1:2671)
>     at Object.o [as fire] (6Hy0l7O248Q6ir-oX_Eoni2EIwg.br.js:1:2904)
>     at l (_fYK6wF8xyDca-Q1gaSZgCGfh6M.br.js:1:15451)
>     at a (_fYK6wF8xyDca-Q1gaSZgCGfh6M.br.js:1:16065)
>     at Object.ht [as triggerSydFSCQueryWithContext] (_fYK6wF8xyDca-Q1gaSZgCGfh6M.br.js:1:16148)
>     at si (A4oJbKqB-nXnwlRIr1h2zsJrTsY.br.js:1:13785)

**Comment by anaclumos** [comment]
Hi Tefery,

By "Scroll Down", do you mean to the direction to the top (where the chat began) or to the bottom (where the regular link-based search results are)? If you mean the latter, AFAIK, this is also present on Edge and is a problem of Bing Chat ATM.

**Comment by Tefery** [comment]
It's curious, on my personal computer it doesn't happen to me with Edge, but it does happen to me on my work computer.
