### ISSUE TITLE
Firefox Japanese Kanji Conversion Error

### ISSUE THREAD

**Issue by TomOttoDX** [anaclumos/bing-chat-for-all-browsers#21]
When inputting Japanese, the Enter after conversion from kana characters to kanji characters is not interpreted separately from the Enter before the Enter for sending, but is sent by pressing Enter to confirm the conversion.
This is probably not limited to Japanese, but can occur when typing in languages that require conversion, such as Korean, Chinese and other mainly Asian languages.

**Comment by anaclumos** [comment]
Hi TomOttoDX,

Thank you for bringing this issue to my attention. As someone who takes i18n seriously, I understand how frustrating it can be to encounter such problems. I'm sorry to hear that you had a hard time with it.

As a native Korean speaker, I use Bing with the Korean language quite often and haven't experienced the issue you described so far. To investigate further, please provide me with some additional information.

- Please let me know which **browser** and **operating system** you use.
- Please let me know if you use any **third-party input method** to type Japanese.
- Finally, I suggest testing Bing on Microsoft Edge to see if the issue persists. If the problem also occurs on Edge, it is likely a problem with Bing itself.

**Comment by TomOttoDX** [comment]
It turns out that in Korean, unlike Japanese, the words you type are combined by themselves to form a different reading. If that is the case, the same situation may not occur in the case of Korean input.
I have taken Gifs of each, but still there is no problem in Edge, but in the combination of Firefox and extensions, when converting to kanji after inputting hiragana in romaji input, it may be sent at the time of the first Enter (deciding where to convert kanji), so even if you try to input the rest of the text, it will be broken off and sent to Bing chat incoherently. (The general input method is to press Enter after converting to kanji to determine the conversion destination, and then press Enter again to send the data.)

OS : Windows 11 22H2 22621.1265
Browser : Firefox

Firefox(No extensions other than Bing chat for all browsers, tested using a different profile to the one normally used).
![firefox_WS2MnNSwfd](https://user-images.githubusercontent.com/47512014/221756305-ad9b819f-c9d6-41d1-adc5-d0eb1e73ecaf.gif)

Edge.
![msedge_fTMciwzHR1](https://user-images.githubusercontent.com/47512014/221756401-fdcf9356-b133-4d05-99c2-e433fd40f2f3.gif)

**Comment by anaclumos** [comment]
Thank you for the information. I may find this hard to debug since I do not know Japanese. However, based on your description, this sounds like a `useEffect` style bug, where the Bing AI tries to give you autocompletion, where that feature collides with how Firefox handles JavaScript. I will try to investigate it, but please understand this may take some time.

Any help will be highly appreciated!

**Comment by ngoclong19** [comment]
It looks like the issue is resolved on Firefox 112.0.2, Windows 10, using Microsoft IME.
