### ISSUE TITLE
Scrolling does not work on Firefox (

### ISSUE THREAD

**Issue by U-bog** [anaclumos/bing-chat-for-all-browsers#24]
Please help solve the scrolling problem. I’m on GitHub for the first time, so I think you’ll understand me. I know I need to set layout.css.overflow-overlay.enabled to true in about:config, but I don’t know how to do it. Where do I put it? Please explain to me the points if possible

**Comment by Shrinks99** [comment]
Go to about:config, search for `layout.css.overflow-overlay.enabled`, double click "False" to set it to "True".

![Screenshot 2023-03-02 125314](https://user-images.githubusercontent.com/5672810/222511363-79b98626-ed4a-42ce-a56c-a8a68980fc3c.png)

**Comment by fullerenedream** [comment]
> Go to about:config, search for `layout.css.overflow-overlay.enabled`, double click "False" to set it to "True".
> 
> ![Screenshot 2023-03-02 125314](https://user-images.githubusercontent.com/5672810/222511363-79b98626-ed4a-42ce-a56c-a8a68980fc3c.png)

I did this and updated my Firefox to the latest version. Alas, scrolling still doesn't work.

**Comment by U-bog** [comment]
Where to find about:config? Sorry to ask such silly questions

**Comment by TURING-V2** [comment]
ask bing

**Comment by U-bog** [comment]
Thank you for your help!! Sorry I’m so stupid, I didn’t know it needed to fit into firefox

**Comment by tom-321** [comment]
If you have uBlock Origin you can use: `bing.com##.scroller-enabled:style(overflow:auto !important;)`
in your filter list :)

**Comment by fullerenedream** [comment]
Thank you tom-321! My scrolling is fixed now! Also I love the reduced visual clutter :D

**Comment by Aryadev19** [comment]
> 

Thanks man now working smoothly, just a script change!

**Comment by aemonge** [comment]
Can we add this an extended README?
