### ISSUE TITLE
the scrolling does not work in my firefox which version is 102.8.0esr (64-bit)

### ISSUE THREAD

**Issue by lovenix4fun** [anaclumos/bing-chat-for-all-browsers#27]

**Comment by anaclumos** [comment]
Can you confirm if you completed the following?

-    Set layout.css.overflow-overlay.enabled to true in `about:config`
-    Update to the latest version of Firefox

**Comment by lovenix4fun** [comment]
yes, I did, it doesn't work
![image](https://user-images.githubusercontent.com/60577999/223003216-cb6b99c0-90a5-49c1-b3e5-a86ea8d04d83.png)

**Comment by lovenix4fun** [comment]
![image](https://user-images.githubusercontent.com/60577999/223003581-fc185e6c-a96a-4537-a683-78330d47b145.png)

**Comment by anaclumos** [comment]
It seems like you are on an extended support release. Is there a reason for that? Otherwise, the latest Firefox version is 110 (as of 2023-03-05). Do you mind updating to it?

**Comment by lovenix4fun** [comment]
It's a compromise, would works, thx.
