### ISSUE TITLE
please make it available for safari.

### ISSUE THREAD

**Issue by varud** [anaclumos/bing-chat-for-all-browsers#28]

**Comment by anaclumos** [comment]
Confirmed. I will work on it after finishing my exams. Meanwhile, if you have some dev knowledge, you can follow this [guide](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari) to convert it yourself.

**Comment by raiyansarker** [comment]
I wanted to make something like this extension on safari after finding this issue but I just realised, you don't need any extension on safari. 
You can easily change user agent in safari. First, go to `Settings -> Advanced -> Enable "Show Develop menu in menu bar"`. That would enable develop menu. Go to bing and tap on `Develop -> User Agent -> Select "Microsoft Edge - Macos"` and you are good to go.

**Comment by OdynOOb** [comment]
> I wanted to make something like this extension on safari after finding this issue but I just realised, you don't need any extension on safari.
> You can easily change user agent in safari. First, go to `Settings -> Advanced -> Enable "Show Develop menu in menu bar"`. That would enable develop menu. Go to bing and tap on `Develop -> User Agent -> Select "Microsoft Edge - Macos"` and you are good to go.

This did not work for me ?
I changed the Agent ti Edge, but I still get the "Download Microsoft Edge" message:
<img width="234" alt="image" src="https://user-images.githubusercontent.com/2715413/227745249-7acad5b9-6753-4bcd-8ab6-31edda3f4476.png">

**Comment by Aleksandir** [comment]
> > I wanted to make something like this extension on safari after finding this issue but I just realised, you don't need any extension on safari.
> > You can easily change user agent in safari. First, go to `Settings -> Advanced -> Enable "Show Develop menu in menu bar"`. That would enable develop menu. Go to bing and tap on `Develop -> User Agent -> Select "Microsoft Edge - Macos"` and you are good to go.
> 
> This did not work for me ? I changed the Agent ti Edge, but I still get the "Download Microsoft Edge" message: <img alt="image" width="234" src="https://user-images.githubusercontent.com/2715413/227745249-7acad5b9-6753-4bcd-8ab6-31edda3f4476.png">

**Comment by Aleksandir** [comment]
> > I wanted to make something like this extension on safari after finding this issue but I just realised, you don't need any extension on safari.
> > You can easily change user agent in safari. First, go to `Settings -> Advanced -> Enable "Show Develop menu in menu bar"`. That would enable develop menu. Go to bing and tap on `Develop -> User Agent -> Select "Microsoft Edge - Macos"` and you are good to go.
> 
> This did not work for me ? I changed the Agent ti Edge, but I still get the "Download Microsoft Edge" message: <img alt="image" width="234" src="https://user-images.githubusercontent.com/2715413/227745249-7acad5b9-6753-4bcd-8ab6-31edda3f4476.png">

This works when you use bing as your search engine and put Safari into "edge development mode", it does not work for actual downloading the extension, only the web app its self.

I hope this makes sense ☺️

**Comment by paxcoder** [comment]
it is not working after converting, I enabled it and it stil prohibits me from using bing.
