### ISSUE TITLE
Move to `declarativeNetRequestWithHostAccess` to Prevent Displaying Warnings

### ISSUE THREAD

**Issue by iandunn** [anaclumos/bing-chat-for-all-browsers#29]
When I go to install the extension, Chrome says it can "Block content on any page". Why is that needed? I don't trust a random extension with permissions it doesn't seem to need.

**Comment by anaclumos** [comment]
That is from `declarativeNetRequest`, required to modify the request as if the request was from the Edge browser. I will move to `declarativeNetRequestWithHostAccess`, which will not show the warning. For reference: [Block API requests via chrome extension and demystifying permission warnings - Manifest v2 and v3](https://gourav.io/blog/block-api-requests-chrome-extension)

<img width="400" alt="image" src="https://user-images.githubusercontent.com/31657298/223210820-86a6199d-b6b6-4513-aced-1be92cc3070c.png">

Meanwhile, if you have any concerns with the integrity of the extension, you can inspect the source code and build it yourself.

Thank you so much.

**Comment by iandunn** [comment]
That sounds good, thanks!
