### ISSUE TITLE
Set Edge Mobile UA for Firefox Android

### ISSUE THREAD

**Issue by rany2** [anaclumos/bing-chat-for-all-browsers#3]

**Comment by anaclumos** [comment]
Confirmed. I do not have an Android device and do not know how the Extension system works in Android Firefox. Can you give me more context on it?

**Comment by rany2** [comment]
I propose that before setting header.value in the background.ts, add a check to see if the user-agent matches a mobile UA (it would be enough to see if header value contains Android in it with a regex). If it matches the Firefox Android UA, then set Microsoft Edge Android's User Agent else fallback to the desktop Edge UA.

Edge UA is `Mozilla/5.0 (Linux; Android 13; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36 EdgA/110.0.1587.41`.

**Comment by rany2** [comment]
That way it wouldn't break the "view as desktop site" option.

**Comment by anaclumos** [comment]
Released v1.0.1. Please take a look!
