### ISSUE TITLE
extension works on Chrome, but not on Opera GX.

### ISSUE THREAD

**Issue by RockE32** [anaclumos/bing-chat-for-all-browsers#30]
Hi, I really appreciate your work, but this extension doesn't work on the Opera GX browser, which is a chromium browser.

I test it on Google Chrome, it works well.

Even thought Opera GX is not a very popular browser or common one, but I would appreciate if you could look into this issue.

**Comment by anaclumos** [comment]
Thanks. We already have it tracked on #2 but do not have any solid progress. If you know anything about Opera not respecting UA changing extensions, contributions will be more than welcomed.
