### ISSUE TITLE
Bing chat summarize

### ISSUE THREAD

**Issue by Luunii** [anaclumos/bing-chat-for-all-browsers#35]
Is it possible to make this feature available for all browsers aswell?: https://www.reddit.com/r/bing/comments/116r3av/bing_chat_can_read_and_summarize_pdfs/?xpromo_edp=enabled

**Comment by anaclumos** [comment]
This is extremely hard since Microsoft only made an exception for edge browsers. Meanwhile, you can use this website (not mine) [ChatPDF - Chat with any PDF!](https://www.chatpdf.com/)

**Comment by anaclumos** [comment]
But I welcome any implementation discussions from users. If it turns out to be a relatively simple fix, I will implement it.

**Comment by Luunii** [comment]
Damn your response times are crazy haha …and that during your midterms … thank you for the consideration and the temporary workaround and good luck on the exams

**Comment by Luunii** [comment]
Damn your response times are crazy haha … and that during your midterm stress … thank you for the consideration and the temporary workaround and good luck on your exams
