### ISSUE TITLE
YouTube on Firefox bug

### ISSUE THREAD

**Issue by goldgrape** [anaclumos/bing-chat-for-all-browsers#36]
After installing this extension, YouTube UI seems to be zoomed in on Firefox.(only 3 videos are showing on row rather than 4 videos as it used to be) Does this have to be something with its CSS settings?

**Comment by anaclumos** [comment]
Hi, I am using FF and do not have a problem. It does not touch anything outside of bing.com, and it does not touch any of the CSS as, well. Maybe it's a different setting you changed recently / different extension that got updated?

**Comment by goldgrape** [comment]
Thank you for your comment! Maybe it's an issue on my end or other extensions
