### ISSUE TITLE
Unable to scroll

### ISSUE THREAD

**Issue by daveboy2000** [anaclumos/bing-chat-for-all-browsers#37]
For some reason, when using Bing AI Chat with Firefox using this plugin, I am unable to scroll up or down, making it impossible to read past answers in a thread or scroll down to see the next chat messages whenever the bot designs to post a few photos.

**Comment by blaise-io** [comment]
See https://github.com/anaclumos/bing-chat-for-all-browsers#-firefox-users-%EF%B8%8F 

### 🦊 Firefox Users ‼️

- ‼️ Set `layout.css.overflow-overlay.enabled` to `true` in `about:config`!
- ‼️ Update to the latest version of Firefox!

Otherwise, the scrolling will not work! 💔

**Comment by git2013vb** [comment]
I have the same problem, Setting the hack in `about:config` the scroll still not do the magic :)
I use Debian 11 and  firefox 102.9.0esr (64-bit) the latest in my SO I guess

**Comment by anaclumos** [comment]
102.9.0esr does not support the option. Would you mind updating to v110 or up?
