### ISSUE TITLE
Can this be also made as a tampermonkey script? for Android Firefox.

### ISSUE THREAD

**Issue by NithinMJose** [anaclumos/bing-chat-for-all-browsers#38]
Can this be also made as a tampermonkey script, for Android Firefox.
Android firefox only supports a limited number of extensions, but it supports tampermonkey, so if this spoof can be made as a userscript, we dont have to use Edge just to access Bing GPt in android device too.
Thanks for the extension btw, i use Bing a lot, its a life saver.

**Comment by anaclumos** [comment]
I am unsure of how to use tampermonkey, but if it has UA access and declarative net request abilities, then it should be possible. PRs are welcome!

**Comment by ArjixWasTaken** [comment]
I don't think tampermonkey can patch UA and net calls.
The only ways to do it is by patching `XMLHttpRequest` and `window.fetch`, and that means you cannot do it for network calls made by the browser and not the page.
