### ISSUE TITLE
The scrolling doesn't work for Waterfox

### ISSUE THREAD

**Issue by HildaJ** [anaclumos/bing-chat-for-all-browsers#39]
This extension can be installed on Waterfox 5.1, a forked browser from firefox, but I cannot found **layout.css.overflow-overlay.enabled** in its **about:config**.

**Comment by anaclumos** [comment]
What is the "Firefox" version of Waterfox? The `layout.css.overflow-overlay.enabled` was just added to FF, so it may not be shipped to other distros.

**Comment by HildaJ** [comment]
Thanks for you response. You're right. I found that latest version of Waterfox is based on Firefox 102.
