### ISSUE TITLE
Add support for Bing AI sidebar URL

### ISSUE THREAD

**Issue by R0M4N0F5K7** [anaclumos/bing-chat-for-all-browsers#41]
Just found out that you can actually access the Bing AI sidebar in every browser via the urls:

https://edgeservices.bing.com/edgediscover/query?&lightschemeovr=1
https://edgeservices.bing.com/edgediscover/query?&darkschemeovr=1

Using this would allow for a better layout (especially on mobile), dark mode and using the compose feature. Interestingly the url already loads and the text generation in "compose" seems to work on firefox mobile, just the "chat" doesn't show up. Maybe some more flags required to make it fit into the window?

Correct display in Kiwi Android with Edge User agent:
![Screenshot_20230316-000732~2](https://user-images.githubusercontent.com/15329506/225466456-d10092d0-d3b2-4618-a05f-0dc9f1bb527d.png)

In firefox android (empty):
![Screenshot_20230316-000901~2](https://user-images.githubusercontent.com/15329506/225466663-2d14732f-f74e-4c02-a946-b7c44836b90d.png)

**Comment by anaclumos** [comment]
Thank you for the issue. Would the request be adding `https://edgeservices.bing.com` for the modification list?

**Comment by R0M4N0F5K7** [comment]
Sorry for the late response. I played around a bit and it seems to me that this link doesn't even check what browser you are using, most likely because microsoft didn't expect anyone to inspect and reuse the url of their side bar. It needs just some querie params, e.g.:

https://edgeservices.bing.com/edgediscover/query?&darkschemeovr=1&FORM=SHORUN&udscs=1&udsnav=1&setlang=en-GB&features=udssydinternal&clientscopes=windowheader,coauthor,chat,&udsframed=1

The only issue seems to be how it is displayed in Firefox as the chat window is of screen, which is not happening in other browsers. With some taping around the keyboard pops up eventually and after some inputs the chat appears and displays correctly...

I suppose I was just hoping for another fix like your "if you use firefox set layout.css.overflow-overlay.enabled to true in about:config!" advice. (Sadly that doesn't seem to fix it on that page)

**Comment by nonetrix** [comment]
This would be great since it allows you to also read the pages content, hope to see this added so I can move away from Edge

**Comment by nonetrix** [comment]
It is also able to just view the pull page contents which is what I was referring to, I think this should be possible in theory but might become a issue with manifest v3 in the near future
