### ISSUE TITLE
The extension is not working anymore 

### ISSUE THREAD

**Issue by wd** [anaclumos/bing-chat-for-all-browsers#42]
will be redirected to a link: https://www.bing.com/search?toWww=1&redig=5AC71C840EC44D94A209130E132FB9BF&q=Bing+AI&showconv=1

**Comment by anaclumos** [comment]
Do you mean is _not_ working anymore?

**Comment by dvygolov** [comment]
Yep, it doesn't work

**Comment by anaclumos** [comment]
<img width="910" alt="image" src="https://user-images.githubusercontent.com/31657298/225768096-bb1982dd-5cdf-48d5-8b01-87e5334a9fb5.png">

Strangely, it's still working for me...

**Comment by Alpengreis** [comment]
@wd Which browser do you use?

PS: There is a report on URL https://addons.mozilla.org/de/firefox/addon/bing-chat-for-all-browsers/reviews/?score=4 too which says it doesn't work anymore ...

**Comment by PranavBhattarai** [comment]
@Alpengreis Here is the weird fix that worked for me:
- Ctrl + H = Histroy
- Select any **bing.com** URL
- Click forget about this site
- Re-login (or let it automatically log in)

It starts to work again.
![image](https://user-images.githubusercontent.com/32763112/225789053-2f0cbdac-740f-4545-bf1d-6a383563db73.png)

I'm using it on Firefox 110 in Fedora 37.

_Only issue I think this extension is not dealing with; is the new URL i.e. "bing.com/new" which gives the user to use ChatGPT4 as mentioned by **XDA-Developers** and **theVerge** articles._

**Comment by anaclumos** [comment]
> Only issue I think this extension is not dealing with; is the new URL i.e. "bing.com/new" which gives the user to use ChatGPT4 as mentioned by **XDA-Developers** and **theVerge** articles.

Can you give me a reference? Bing Chat was already running on GPT-4 from the beginning.

> "If you’ve used the new Bing preview at any time in the last five weeks, you’ve already experienced an early version of this powerful model" [Confirmed: the new Bing runs on OpenAI’s GPT-4 | Bing Search Blog](https://blogs.bing.com/search/march_2023/Confirmed-the-new-Bing-runs-on-OpenAI%E2%80%99s-GPT-4)

> Microsoft’s new AI-powered Bing chatbot has been relying on the newly announced GPT-4 model **all along**. [Microsoft was already using OpenAI’s GPT-4 model for the Bing AI chatbot - The Verge](https://www.theverge.com/2023/3/14/23639928/microsoft-bing-chatbot-ai-gpt-4-llm)

AFAIK the "New" Bing they are referring to is the chat interface in general, compared to the traditional Bing.

**Comment by PranavBhattarai** [comment]
Thanks for the confirmation. In "Bing Chat", the user can't really ask what version of ChatGPT it is using, it just says, it is not allowed to say the details.

The "wishlist" is what confused me. I thought the new ChatGPT4 requires a separate "wishlist".

**Comment by wd** [comment]
I use firefox on Mac. @PranavBhattarai's work around doesn't work for me.

**Comment by lcrespom** [comment]
It seems to work for me in Chrome, but when I type in the chat box, each character gets immediately eliminated. I can use a workaround by typing the question elsewhere, then copying and pasting in in the chat box, but that is not very convenient.

**Comment by PrissyPineapple** [comment]
I'm on Firefox and it's not working for me either. When I hit the "chat" button it displays the generic "Chat mode is only available when you have access to the new Bing." message.

I do have access to the new Bing, and I can use it on Edge and on the Bing app.

**Comment by elvismercado** [comment]
I've been using this this extension on Brave browser for a while, and today while asking some questions i suddenly get a popup telling me to download Edge browser.

![image](https://user-images.githubusercontent.com/3658208/226042971-c7689dd7-60f4-4241-9380-2e438440d1cd.png)

**Comment by HildaJ** [comment]
> I've been using this this extension on Brave browser for a while, and today while asking some questions i suddenly get a popup telling me to download Edge browser.
> 
> ![image](https://user-images.githubusercontent.com/3658208/226042971-c7689dd7-60f4-4241-9380-2e438440d1cd.png)

I got a popup yesterday and found that I was put back in waitlist after being given access to new Bing. I'm not sure if this extension causes it.

**Comment by Lanme** [comment]
Delete bing cookies and restart works for me. But sometimes I will get this: Sorry, looks like your network settings are preventing access to this feature

**Comment by wd** [comment]
> @PranavBhattarai 's workaround works for me. I don't process it correctly the last time.

Since I'm able to access bing chat in firefox on mac now. Feel free to close this issue. @anaclumos

**Comment by wd** [comment]
I'm back again.. I'm able to open the website and input questions, but I always receive this error `Sorry, looks like something went wrong.` 😓..

**Comment by anaclumos** [comment]
It's probably Bing Chat and OpenAI being errorful. Bing will probably have their own Azure instance but based on [status.openai.com](https://status.openai.com) OpenAI is struggling with the demand. It may be similar to Bing chat as well.

**Comment by kdvolder** [comment]
Stopped working for me also just now. I can still use bing chat from Chrome if I use Chrome dev tools to change user agent. (But this extension suddenly stopped working)

**Comment by PrissyPineapple** [comment]
> Stopped working for me also just now. I can still use bing chat from Chrome if I use Chrome dev tools to change user agent. (But this extension suddenly stopped working)

The opposite happened to me. After weeks of not working at all, it suddenly started working perfectly. I checked to see if maybe there was an update, but no. It just started working randomly. 

It seems like Bing is just temperamental.
