### ISSUE TITLE
Not Working on Opera GX for Windows

### ISSUE THREAD

**Issue by NerdyWanKenobi** [anaclumos/bing-chat-for-all-browsers#43]
This extension works for me on both Firefox and Chrome but when I try it on Opera GX (my browser of choice and the browser I used before Microsoft came out with Bing Chat and effectively forced me to switch to Edge), it doesn't work and it still just shows the whole "Open in Edge" spiel.  Opera works with most Chrome extensions so I'm not sure why it's not working.  I made sure "Allow access to search page results" was enabled (Opera disables that in extensions by default for some reason which makes a lot of extensions not work until you enable it) and it's still not working.  I am on the latest version of Opera GX so I don't think it's a version issue.  Maybe there's some setting that needs to be changed in Opera for it to work, similar to "layout.css.overflow-overlay.enabled" in Firefox but I'm not sure exactly what that setting would be.

**Comment by anaclumos** [comment]
Yes, we are tracking this issue on #2. AFAIK it seems like Opera is blocking changing UAs.
