### ISSUE TITLE
Small qol issue

### ISSUE THREAD

**Issue by Aerasyn** [anaclumos/bing-chat-for-all-browsers#44]
Been using this on firefox. Was wondering if you could make it so the little interactive window when clicking the extension could close itself after opening bing chat on a new tab. The window stays open and it's just annoying to have to manually close it then go play with Bing.

**Comment by anaclumos** [comment]
If I start typing my question, or just click anywhere else, the window goes away. May I ask if this is not enough for you?


https://user-images.githubusercontent.com/31657298/225768749-6af1895c-de31-4556-b0d0-d41d676e7897.mov

**Comment by Aerasyn** [comment]
Oh, yep lol. Didn't even check for that. My mistake :)
