### ISSUE TITLE
Copy-paste bug in line 43 of background.ts?

### ISSUE THREAD

**Issue by lcrespom** [anaclumos/bing-chat-for-all-browsers#45]
Reading the source code of `background.ts`, I see these two lines:

```JavaScript
        if (header.value?.toLowerCase().includes('mobile')) header.value = uaMaker(MOBILE_UA_SUFFIX, true)
        else header.value = uaMaker(MOBILE_UA_SUFFIX, false)
```
Shouldn't the second line use `DESKTOP_UA_SUFFIX` instead of `MOBILE_USA_SUFFIX`?

**Comment by anaclumos** [comment]
You are right. We haven't caught this error because the `uaMaker` change has not shipped yet.
