### ISSUE TITLE
No code 'window' and table not shown as table

### ISSUE THREAD

**Issue by fantacola** [anaclumos/bing-chat-for-all-browsers#46]
In Forefox

1. Instead of this:

prid | date | status
-- | -- | --
1 | 01.02.2021 | open
1 | 04.01.2022 | approved
1 | 05.03.2022 | implemented
1 | 24.04.2022 | closed

it's shown as this:

1 01.02.2021 open 1 04.01.2022 approved 1 05.03.2022 implemented 1 24.04.2022 closed 2 01.02.2021

2. in the answer the code is not in a 'special' box for code..it's just plain text

**Comment by anaclumos** [comment]
Hi, thank you for the report. Do you mean that Bing does not reply in tables?

**Comment by anaclumos** [comment]
Feel free to reopen the issue if it persists.
