### ISSUE TITLE
other languages

### ISSUE THREAD

**Issue by NeilRiver** [anaclumos/bing-chat-for-all-browsers#47]
Hello friend, apparently you hardcoded somewhere so that the chat bing answered in English. Please make the region auto-detect or let us choose the language yourself. With all my desire, it is more convenient for me to read the answers in my native language. Thank you in advance!

**Comment by anaclumos** [comment]
What OS & Browser are you using? I did not hardcode anything and I can use Bing Chat with Korean just as normal.

**Comment by NeilRiver** [comment]
Hi, sorry I don't know how it works, I opened it today for testing and it spoke my local language. Close this issue.

**Comment by Bubbu0129** [comment]
More on this topic.
Can there be an option to choose language? Bing AI opt for the display language in your MS account. But, in my use case, I need to change to English everytime I launch the plugin. 
Adding `setlang` parameter in the URL may just work.
