### ISSUE TITLE
Chat mode is only available if you have access to the new Bing

### ISSUE THREAD

**Issue by NeilRiver** [anaclumos/bing-chat-for-all-browsers#48]
Can you fix this isue ?

https://geekermag.com/how-to-use-new-bing-chat-mode-in-google-chrome/

**Comment by anaclumos** [comment]
Can you access it on MS Edge? You will need an account with Bing access.

**Comment by PrissyPineapple** [comment]
I have the same issue. I can access new bing on the Android app as well as on MS edge. When I try to open in on Firefox with the extension it shows that message.

**Comment by TheVoxcraft** [comment]
Same issue, had access a few days ago

**Comment by Bennett-Fourr** [comment]
Try clearing your browser cach it fixed it for me

**Comment by vic233333** [comment]
This problem may also happen when using edge. Try these.
* Refresh the page or clear the browser cache and cookies. 
* Make sure the network connection is working well.

**Comment by anaclumos** [comment]
Will add troubleshooting guide soon.

**Comment by anaclumos** [comment]
Please clear the cache and cookies and try again. Could you let me know if the issue continues?
