### ISSUE TITLE
Firefox: scrolling doesn't work; needs layout.css.overflow-overlay.enabled set to True

### ISSUE THREAD

**Issue by AxelBoldt** [anaclumos/bing-chat-for-all-browsers#49]
In the Firefox extension, scrolling does not work correctly, unless in about:config you set
layout.css.overflow-overlay.enabled
to True.

**Comment by anaclumos** [comment]
Yes. It's mentioned on the README, which should pop up right after you install. Do you want a more prominent alert?

**Comment by AxelBoldt** [comment]
Sorry, I didn't see it there, I guess I didn't pay attention. I read it later in one of the reviews. It's probably fine the way it is; there will always be stupid users...
