### ISSUE TITLE
Not Working on Firefox behind a corporation proxy with ntlm auth

### ISSUE THREAD

**Issue by danxxcruz** [anaclumos/bing-chat-for-all-browsers#50]
Extension not working in Firefox 111. I'm using job PC behind a squid proxy with basic auth

**Comment by anaclumos** [comment]
Bing behaves finicky behind any AdBlock or VPN. Can you have Bing working on Edge under the same condition?

**Comment by anaclumos** [comment]
Please clear the cache and cookies and try again. Could you let me know if the issue continues?
