### ISSUE TITLE
Cannot scroll on Firefox

### ISSUE THREAD

**Issue by Dhyey17** [anaclumos/bing-chat-for-all-browsers#51]
When the response is received from bing, I cannot scroll more than what's currently being displayed, neither upwards nor downwards. I've tried clearing the cache and restarting the browser but the issue still persists. I'm using the 102.8.0esr (64-bit) version of Firefox

**Comment by anaclumos** [comment]
v102 does not support layout.css.overflow-overlay.enabled option. Do you mind upgrading to ~v110?

**Comment by Alpengreis** [comment]
@Dhyey17 

And you can't install Firefox as non ESR version? Means, from the Site ...

https://www.mozilla.org/en-US/firefox/all/#product-desktop-release

... select Linux 64-bit?

There is 111.0.1 available.

**Comment by jonasSOPAT** [comment]
i can't scroll either. Firefox v111.0.1. windows 10 64bit
