### ISSUE TITLE
Firefox may clash when using Chinese input method

### ISSUE THREAD

**Issue by vic233333** [anaclumos/bing-chat-for-all-browsers#52]
This is what I did to Firefox. I can stably reproduce it on my Laptop.
1. Switch to the full page to talk with Bing.
2. Say something to it.
3. Let Bing finish answering the question.
4. Click `Clear` button to clear the context.
5. Focus on the input box
6. Switch to a third-party Chinese input method. (If you use the Microsoft input method, you will find that you cannot type Chinese, but this will not cause the clash of Firefox)
7. Press any button on the keyboard.
8. Firefox clashes.

Some Clash reports (with not other add-ons):
* [https://crash-stats.mozilla.org/report/index/5efe0b48-99c6-4dc6-a3a8-4f1240230323]()

Some Clash reports (with other add-ons) (You can ignore other add-ons because I have ruled out issues with these add-ons):
* [https://crash-stats.mozilla.org/report/index/bp-9ed04945-8888-40f2-a96c-785bf0230323]()
* [https://crash-stats.mozilla.org/report/index/bp-2cd8071e-f983-441f-9254-035140230323]()
* [https://crash-stats.mozilla.org/report/index/bp-d388c917-12c5-433d-985d-8b5950230323]()
* [https://crash-stats.mozilla.org/report/index/bp-6723d771-c748-49c3-8539-eddbc0230323]()
* [https://crash-stats.mozilla.org/report/index/bp-451983f0-588a-479d-ae96-c7c400230323]()
* [https://crash-stats.mozilla.org/report/index/bp-a5905320-4360-444c-a1cf-e1d230230323]()

Here is the third-party Chinese input method I am using: [https://pinyin.sogou.com/zhihui/]()

This may let you avoid the issue.
1. Use Microsoft input method when using New Bing on Firefox.
2. Switch the style of New Bing after you click `Clear` button.

Tip: This bug will happen every time after you click `Clear` button when talking to New Bing in the full page.

**Comment by anaclumos** [comment]
Hi, this will be very hard to debug for me, who does not speak Chinese. Any help would be heavily appreciated.

**Comment by vic233333** [comment]
Good news. I cannot reproduce it on Firefox Beta `112.0b8 (64-bit)`. It seems that this bug will be fixed in the next version.
In addition, `layout.css.overflow-overlay.enabled` is default `true` in that version.
