### ISSUE TITLE
Bing Image Creator Feature in Chat is not working which is available in edge

### ISSUE THREAD

**Issue by SaadhJawwadh** [anaclumos/bing-chat-for-all-browsers#54]
Bing image creator within chat is not working I tried overriding latest user agent yet it's not working

**Comment by vic233333** [comment]
Bing image creator in my computer is working well. I'm using Firefox 111.0.1 (64bit). My system is Windows 10 Home Edition 22H2.

**Comment by SaadhJawwadh** [comment]
The website is working for me as well. The Creative mode in bing chat can also generate images that is not working.

**Comment by vic233333** [comment]
> The website is working for me as well. The Creative mode in bing chat can also generate images that is not working.

Do you mean Bing says it will draw a picture but it doesn't draw it?

**Comment by SaadhJawwadh** [comment]
No, Bing says it cannot draw pictures in Firefox but, for the same prompt it is generating 4 pictures in Edge.

**Comment by vic233333** [comment]
> No, Bing says it cannot draw pictures in Firefox but, for the same prompt it is generating 4 pictures in Edge.

I didn't suffer that problem.
And why New Bing know you are using Firefox? It will not allow you to use New Bing in Firefox and force you to use Edge.

Could you give a screenshot? So I can know what exactly happened.

**Comment by SaadhJawwadh** [comment]
> > No, Bing says it cannot draw pictures in Firefox but, for the same prompt it is generating 4 pictures in Edge.
> 
> I didn't suffer that problem.
> And why New Bing know you are using Firefox? It will not allow you to use New Bing in Firefox and force you to use Edge.
> 
> Could you give a screenshot? So I can know what exactly happened.

I just tried it to give a screen and now it's working perfectly 😍 I don't know the reason.

When I try to enter a create prompt

Old behavior: As a LLM i can't create images but, I can describe

New behavior: Giving 4 images.

Thanks a bunch for communicating as well.
