### ISSUE TITLE
Not working for chrome

### ISSUE THREAD

**Issue by UKMIITB** [anaclumos/bing-chat-for-all-browsers#56]
It says chat mode is only available when you have access to new bing

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/36126610/228327629-d5e0b168-434a-4009-b486-be206cdaeb85.png">

Is it like I am on waitlist for this ?

**Comment by anaclumos** [comment]
I don't think so... that's weird. What's your OS & Desktop environment & Browser Version?

**Comment by vic233333** [comment]
It seems to be the same issue with #48.
Please make sure you have access to New Bing, then clear the browser's cache and cookies and refresh the page.

**Comment by Sheldontao** [comment]
you should clear your browser's cache and cookies in the meanwhile you log in

**Comment by anaclumos** [comment]
Please clear the cache and cookies and try again. Could you let me know if the issue continues?
