### ISSUE TITLE
Bug - Continuation After Prompt to Link Work and Social Accounts

### ISSUE THREAD

**Issue by slawton3** [anaclumos/bing-chat-for-all-browsers#57]
When signing into an account, I am prompted to share between work and personal accounts.

![Screenshot 2023-03-28 at 2 51 35 PM](https://user-images.githubusercontent.com/23325888/228351775-0e41ff2e-4b90-4580-993b-3f827956c1bc.png)

When I select "Don't connect" I am brought to a blank page and nothing renders on the screen.

**Comment by anaclumos** [comment]
This sounds like MS's problem. Do you have the same problem on Edge?

**Comment by anaclumos** [comment]
Feel free to reopen the issue if the issue persists.
