### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by PhoenixBodrov** [anaclumos/bing-chat-for-all-browsers#58]
I can't open Bing AI in any way. There is no chat, and then i press "Open Bing Chat" it pushes me to search about "Bing AI". I can't use it.

![изображение](https://user-images.githubusercontent.com/100290554/228730864-126e9946-dc38-499d-bb03-38cc3fb7cf12.png)

**Comment by anaclumos** [comment]
Are you logged into Bing? Can you use Bing AI on your Edge browser?

**Comment by puteulanus** [comment]
Same here, logged in already, and can use bing AI in edge with the same account/network.
I'm using Firefox 111.0.1 on Mac, with set layout.css.overflow-overlay.enabled to true.

**Comment by anaclumos** [comment]
Seems like a regional thing; unsure how to fix this. Any thoughts?

**Comment by Essy1245** [comment]
Same issue here. But I think the new chrome update seems to affect this. 
On my other devices that are running Chrome 111.0.5563.111, this extension works fine. 
On devices with Chrome 111.0.5563.147, it does not work. 
![image](https://user-images.githubusercontent.com/80929407/229369666-4aee31f6-27b5-4db6-904a-488b50a6b783.png)

**Comment by anaclumos** [comment]
Based on your screenshots, it seems like you are in China. After some research, I found that Bing Chat is blocked in China.

[New Bing: Sorry, looks like you no longer have access to this - Microsoft Community](https://answers.microsoft.com/en-us/microsoftedge/forum/all/new-bingsorry-looks-like-you-no-longer-have-access/6d21c57f-0484-4a9a-a9ac-c46c706722cc)

Please reopen the issue if ① you are not in China mainland && ② you cleared cache and cookies && ③ the issue still exists.
