### ISSUE TITLE
No input possible

### ISSUE THREAD

**Issue by Stoascheisserkoarl** [anaclumos/bing-chat-for-all-browsers#59]
Can not make any inputs, except for 5 keys it is as if the keyboard is dead.
Browser: Brave

**Comment by anaclumos** [comment]
Please clear the cache and cookies and try again. Could you let me know if the issue continues?

**Comment by Stoascheisserkoarl** [comment]
Problem persists. What I do not understand is that some keys work. Can this be due to the keyboard layout?

**Comment by Stoascheisserkoarl** [comment]
exchanging the header info is probably not enough

**Comment by anaclumos** [comment]
> Can this be due to the keyboard layout?

It could be. What's your keyboard layout & what keyboard input software do you use?

Users also reported that some other extensions which access key input events could interfere with Bing, most notably Video Speed Controller. Any specific extension that comes to your mind that will interfere with Bing?
