### ISSUE TITLE
still redireact to cn.bing.com even I didn't login

### ISSUE THREAD

**Issue by adoin** [anaclumos/bing-chat-for-all-browsers#63]

**Comment by anaclumos** [comment]
Seems like a regional lock. Can you access it on Edge?

**Comment by adoin** [comment]
> Seems like a regional lock. Can you access it on Edge?

Can't, but weeks before it can go to newbing, i have no idea why.
Tried proxy agent live.com bing.com.

**Comment by anaclumos** [comment]
Bing Chat is blocked in China.

[New Bing: Sorry, looks like you no longer have access to this - Microsoft Community](https://answers.microsoft.com/en-us/microsoftedge/forum/all/new-bingsorry-looks-like-you-no-longer-have-access/6d21c57f-0484-4a9a-a9ac-c46c706722cc)
