### ISSUE TITLE
Cannot Download on Firefox Mobile

### ISSUE THREAD

**Issue by Littlemac123** [anaclumos/bing-chat-for-all-browsers#66]
Its not working in android firefox 
![Screenshot_2023-04-06_02-22-15](https://user-images.githubusercontent.com/39867553/230304413-9ae442be-c8af-4eee-a812-8d8377d52368.png)

**Comment by anaclumos** [comment]
I checked that I enabled downloads for Firefox Android. What version are you at?

Everyone else using FF Mobile facing the same problem?

**Comment by meanindra** [comment]
@Littlemac123 I think you can use [Iceraven Browser](https://github.com/fork-maintainers/iceraven-browser) , it is Firefox fork browser and it support almost all Firefox extentions

**Comment by meanindra** [comment]
@anaclumos I am also can confirm that it is not available for Firefox Android

**Comment by anaclumos** [comment]
I am pretty sure I checked the "Firefox for Android" toggle, but just to ensure, I resubmitted the same version. Should be available on store in couple hours.

<img width="2048" alt="Screenshot 2023-04-06 at 4 29 06 PM" src="https://user-images.githubusercontent.com/31657298/230511959-5e2a7677-583f-4941-bfd3-d73f3940503a.png">
<img width="2048" alt="Screenshot 2023-04-06 at 4 30 33 PM" src="https://user-images.githubusercontent.com/31657298/230511966-34e87758-d4fe-489c-a971-409bac6ae642.png">

**Comment by anaclumos** [comment]
It's now live. Can you confirm if the issue is resolved? @Littlemac123 @meanindra

**Comment by meanindra** [comment]
![Screenshot_20230407-083923_Firefox.png](https://user-images.githubusercontent.com/36324543/230533349-15ff6506-02a1-418e-9270-2d83a2b4a523.png)

Still not available

**Comment by pqnhan** [comment]
It looks like you will have to go through a rigorous review to get your addons to work on Firefox Android (stable version).
 As you can see when you visit AMO on Firefox Android, the list of currently installable addons is only one finger.

To be able to install all other addons you need to use a modified version of Firefox Android - as @meanindra suggested above.
 Or use [Firefox Nightly for Developers](https://play.google.com/store/apps/details?id=org.mozilla.fenix).

**Comment by pqnhan** [comment]
Another way is to convert your addons into Userscript and load it with Tampermonkey - already supported on all latest Firefox Android versions.

**Comment by DioEgizio** [comment]
You need to install Firefox beta or nightly, or use forks like fennec

**Comment by Littlemac123** [comment]
> You need to install Firefox beta or nightly, or use forks like fennec

How do you do it on fennec I actually use that

**Comment by DioEgizio** [comment]
See https://www.reddit.com/r/fossdroid/comments/p7mgec/guide_using_most_all_firefox_addons_on_fennec_on/
