### ISSUE TITLE
Cannot

### ISSUE THREAD

**Issue by array** [anaclumos/bing-chat-for-all-browsers#70]
Firefox 112 release
bing-chat-for-all-browsers 1.0.5.1
Click Bing symbol,open explain on bing chat,and click start chat(?,I'm Japanse so "Chatを始める”）, open bing search,not bing chat

**Comment by Gmaia325** [comment]
> Firefox 112 release bing-chat-for-all-browsers 1.0.5.1 Click Bing symbol,open explain on bing chat,and click start chat(?,I'm Japanse so "Chatを始める”）, open bing search,not bing chat

I also encountered the same error in Firefox and for me the solution was when I performed the following steps:

 -   I disabled the add-on (extension) "Decentraleyes"
 -  Then I cleared the cache and cookies
 -   Enabling it (add-on "Decentraleyes") again

**Comment by array** [comment]
I don't use Decentraleyes.
I clear all cache and cookies about bing,but dont work.

**Comment by anaclumos** [comment]
Can you confirm that you can use it on Edge?

**Comment by jeetabhi01** [comment]
Facing same issue on Chrome Version 113.0.5672.24 (Official Build) beta (64-bit) even after clearing cache and cookies

**Comment by anaclumos** [comment]
The screenshot shows that ur not signed into Bing. Can you sign in and try again?

**Comment by anaclumos** [comment]
Everyone, please re-confirm if you 

1. have access to Bing Chat (off the waitlist)
2. clear cache & cookies

Please reopen the issue if the issue persists.
