### ISSUE TITLE
¿No longer working?

### ISSUE THREAD

**Issue by dechenique1** [anaclumos/bing-chat-for-all-browsers#71]
I don't know what changed but it no longer works.  At least in my version of Chrome (112.0.5615.87). I reinstalled and nothing happened.
It is a great product!

**Comment by anaclumos** [comment]
Nothing changed. Can you clear the cache & cookies on Bing and try again?

**Comment by Gmaia325** [comment]
I also encountered the same error in Firefox and for me the solution was when I performed the following steps:
- I disabled the add-on (extension) "Decentraleyes"
- Then I cleared the cache and cookies
- Enabling it (add-on "Decentraleyes") again

**Comment by Gmaia325** [comment]
> I don't know what changed but it no longer works. At least in my version of Chrome (112.0.5615.87). I reinstalled and nothing happened. It is a great product!

I also encountered the same error in Firefox and for me the solution was when I performed the following steps:
- I disabled the add-on (extension) "Decentraleyes"
- Then I cleared the cache and cookies
- Enabling it (add-on "Decentraleyes") again

**Comment by foregroundprocess** [comment]
I'm getting error: "Sorry, it looks like you've been signed out" each time I try to start a conversation. Tried to disable the extension, clear cache and cookies in both Firefox and Edge, but still no luck. In Edge chat is working with no issue.

**Comment by anaclumos** [comment]
@foregroundprocess do you have Bing account that has access to bing chat?

**Comment by fylim** [comment]
Not working for me either. Getting this message "Chat mode is only available when you have access to the new Bing." see attached

![image](https://user-images.githubusercontent.com/5226402/232175744-3d10c051-018f-43d4-a0e9-84b7aefbb7c1.png)

**Comment by anaclumos** [comment]
@fylim You are signed out. Please log in.

**Comment by jeetabhi01** [comment]
@fylim please sign in disable any active ad blocker or vpn on bing.com and try again.

**Comment by foregroundprocess** [comment]
I even got the "Chat mode is only available when you have access to the new Bing" in the Edge browser today. And there was also new sign-in prompt, so it looks like MS has changed something.

> @foregroundprocess do you have Bing account that has access to bing chat?

Yes, I do.

**Comment by fylim** [comment]
I managed to get it to work after upgrading OpenAI account from trial to paid account and recreating the API key for use with Auto-GPT.

**Comment by Prurite** [comment]
No longer works. Displays 'Chat now' button but everytime I click it, it just brings me back to that page.

**Comment by Arku3S** [comment]
It works, here is how i did it:

I disabled all extensions including Bing Chat for All Browsers
I turned off Enhanced tracking protection in settings
I cleared the cache
I cleared bing, live and microsoft cookies (all sites from microsoft)
I turned off and on the browser
I only enabled one Bing Chat for All Browsers extension
I went to bing, logged in and the chat works
After that, I enabled all extensions and Enhanced tracking protection

**Comment by ficool2** [comment]
Ran into this issue despite being signed in and clearing cookies. Fixed it by disabling the extension, attempting to open Bing chat and getting the Edge prompt, then enabling the extension and refreshing the page

**Comment by fullerenedream** [comment]
@ficool2 Thank you! That fixed it for me too.

**Comment by foregroundprocess** [comment]
Yes, that helped me too.
