### ISSUE TITLE
Cannot use Firefox 112 (ReOpen)

### ISSUE THREAD

**Issue by array** [anaclumos/bing-chat-for-all-browsers#72]
anclumos says:

> 1.     have access to Bing Chat (off the waitlist)
> 2.     clear cache & cookies
> 

I tried the above, but it doesn't become a usable normality
off course I use Bing chat with other Browser,Vivaldi and Edge.

**Comment by Arku3S** [comment]
It works, here is how i did it:

I disabled all extensions including Bing Chat for All Browsers
I turned off Enhanced tracking protection in settings
I cleared the cache
I cleared bing, live and microsoft cookies (all sites from microsoft)
I turned off and on the browser
I only enabled one Bing Chat for All Browsers extension
I went to bing, logged in and the chat works
After that, I enabled all extensions and Enhanced tracking protection

**Comment by array** [comment]
I uninstall Firefox 112,and delete Profile Folder. 
so I re-install Firefox112 and use BCfAB,wow,I can USE it.
Thanks.

**Comment by directentis1** [comment]
I can't use Bing Chat on Firefox Android anymore for the past few days, always this annoying prompt, and when I click "Chat now" it immediately opens another tab and repeats like this: /
![](https://i.imgur.com/UWua52M.png)

Maybe M$ changed something on their BingChat?
