### ISSUE TITLE
scrolling doesn't work in tor browser

### ISSUE THREAD

**Issue by cbridget42** [anaclumos/bing-chat-for-all-browsers#73]
I set layout.css.overflow-overlay.enabled to true and updated my browser, but It still doesn't work.

**Comment by cbridget42** [comment]
12.0.4(based on Mozilla Firefox 102.9.0esr), OS Ubuntu 22.04

**Comment by anaclumos** [comment]
FF 102 does not support `layout.css.overflow-overlay.enabled`. Do you mind updating to FF ~110? (Non-ESR)

**Comment by cbridget42** [comment]
Badly. I can't update because it's the latest version for the Tor browser. I have to use the Tor browser because Bing is blocked in my country.

**Comment by anaclumos** [comment]
This will automatically be fixed when the Tor browser releases a new version with a newer FF client.
