### ISSUE TITLE
No longer working on Chrome (gives "Open in Microsoft Edge" window)

### ISSUE THREAD

**Issue by chiaracoetzee** [anaclumos/bing-chat-for-all-browsers#74]
As of just now, when I visit https://www.bing.com/search?q=-&showconv=1 in Chrome the chat view no longer appears, just the web result view. Same URL is working fine in Edge.

If I search for "foo" then click the "Chat" button, I get the pop-up instructing me to "Open in Microsoft Edge". I'm definitely logged into my Microsoft account correctly, I even tried logging out and back in.

Probably a change to their front-end code on Bing site.

**Comment by anaclumos** [comment]
Can you confirm the error happens even if you

- log out from Bing
- clear cache
- clear cookie
- log back into Bing

**Comment by yckim-inqten** [comment]
me too. clearing the cache and logging back in doesn't work.

**Comment by anaclumos** [comment]
I will investigate soon. I am using Chromium but can still use it.

**Comment by nkrackow** [comment]
Same, clearing cache doesn't change things.

**Comment by Xbai-hang** [comment]
Same, and when I clearing the cookie and log in to my account again, I foud my account was lockedIt seems New Bing further blockade of Chinese users,  and cannot be unlocked using the+86 phone number.

The reason given for the ban is: We have detected certain activities that violate our Microsoft service agreement and have locked your account.

**Comment by M1saka10010** [comment]
Same, clearing the cache doesn’t change anything. And I can confirm that it’s not a problem with my account because it works in Edge.

**Comment by yoofish** [comment]
Strangely it works on firefox but not on google chrome, and clearing cache&cookie doesn't work either.

**Comment by shiyuanGame** [comment]
我的也一样，

**Comment by NotTheCoderGb** [comment]
yoyo me too i need to do important questions so this shieet not letting me do it :( im at school chromebook pls help, downloading edge is an option but its not very pratical since the school will know it

**Comment by reagle** [comment]
Unfortunately, MS is probably being more sophisticated in their browser detection.

**Comment by yokoffing** [comment]
Happening to me as well.

**Comment by gitony0101** [comment]
chrome , mac m1 , does not work today

**Comment by cappydino** [comment]
On the chrome web store reviews for the extension, Spencer Powell gives a solution to the problem, by using chrome dev tools to change the browser to Edge.

The link is [here](https://chrome.google.com/webstore/detail/bing-chat-for-all-browser/jofbglonpbndadajbafmmaklbfbkggpo)

**Comment by Mrgaton** [comment]
Same for me

**Comment by anaclumos** [comment]
This is problematic 

https://user-images.githubusercontent.com/31657298/232904399-4e31e89e-b058-4de3-9fa3-f1f4222de8d9.mov

😭 I cannot replicate the problem. Can anyone help me out?

**Comment by sa-mendez** [comment]
> This is problematic sob I cannot replicate the problem. Can anyone help me out?
> Screen.Recording.2023-04-18.at.2.00.12.PM.mov

I am having this issue as well, and can try to help you out.  Let me know how, or if you want to reach out to me directly.

**Comment by anaclumos** [comment]
Everyone, does this version works for you on Chrome (it can be installed on Chrome, although it says firefox)

https://github.com/anaclumos/bing-chat-for-all-browsers/blob/main/release/firefox.zip

**Comment by leynier** [comment]
> Everyone, does this version works for you on Chrome (it can be installed on Chrome, although it says firefox)
> 
> https://github.com/anaclumos/bing-chat-for-all-browsers/blob/main/release/firefox.zip

I tested it and the problem still persists, let me know if you need any information from me? Thanks in advance.

**Comment by shiyuanGame** [comment]
> This is problematic 😭 I cannot replicate the problem. Can anyone help me out?
> 
>  Screen.Recording.2023-04-18.at.2.00.12.PM.mov

Windows chrome  版本 112.0.5615.121（正式版本） （64 位）

**Comment by anaclumos** [comment]
Sharing the status quo:

- A lot of people can still use Bing with this extension. This includes my friends and me; we could not replicate the problem.
- However, the number of people reporting issues about being blocked spiked.
- This is possibly Bing slowly rolling out a new type of browser detection. We are still determining what this is at the moment.
- While some reported that CR/FF version did not work and changing the user agent manually worked, others said changing the user agent did not. For these few users, the methods provided did not work, except for using the native Edge.

I would greatly appreciate any help. i.e., do you have any suggestions?

**Comment by luyang93** [comment]
If I set user agent in chrome devtools without header editor or plugin. I can use new bing in chrome, but it need to keep devtools open.
![image](https://user-images.githubusercontent.com/39150988/232953784-1bbd28e0-9e66-44ec-a103-fb313ecaf003.png)

**Comment by shankar58989** [comment]
Changing the browser identification in developer tools and refreshing the page works for me.

**Comment by shiyuanGame** [comment]
> > If I set user agent in chrome devtools without header editor or plugin. I can use new bing in chrome, but it need to keep devtools open. ![image](https://user-images.githubusercontent.com/39150988/232953784-1bbd28e0-9e66-44ec-a103-fb313ecaf003.png)
> 
> Just open devtools when you refresh the page. When entering the new bing chat page, you can close devtools

Changing the browser identification in developer tools and refreshing the page works for me.

**Comment by anaclumos** [comment]
I think I fixed it! Can everyone check this build?

[main/release/firefox.zip](https://github.com/anaclumos/bing-chat-for-all-browsers/blob/main/release/firefox.zip?rgh-link-date=2023-04-18T22%3A45%3A12Z)

**Comment by shiyuanGame** [comment]
sure!  I’m there.

**Comment by shiyuanGame** [comment]
> I think I fixed it! Can everyone check this build?
> 
> https://github.com/anaclumos/bing-chat-for-all-browsers/blob/main/release/chrome.zip

ok！！ i'm windows10 chrome    I‘m good！ Thank you, developer

**Comment by shiyuanGame** [comment]
Is this bug related to the region?

> > I think I fixed it! Can everyone check this build?
> > https://github.com/anaclumos/bing-chat-for-all-browsers/blob/main/release/chrome.zip
> 
> ok！！ i'm windows10 chrome I‘m good！ Thank you, developer

Is this bug related to the region? I’m in China

**Comment by hui1601** [comment]
> I think I fixed it! Can everyone check this build?
> 
> https://github.com/anaclumos/bing-chat-for-all-browsers/blob/main/release/chrome.zip

![image](https://user-images.githubusercontent.com/24631476/232987691-08e46feb-ba68-4794-84d0-5e422dff5f6f.png)

It's Works!
Chrome 112.0.5615.121, Ubuntu 22.10
Japan.

**Comment by stephane303** [comment]
> > I think I fixed it! Can everyone check this build?
> > https://github.com/anaclumos/bing-chat-for-all-browsers/blob/main/release/chrome.zip
> 
> ok！！ i'm windows10 chrome I‘m good！ Thank you, developer

Yes it works !

**Comment by OnePieceJoker** [comment]
> I think I fixed it! Can everyone check this build?
> 
> https://github.com/anaclumos/bing-chat-for-all-browsers/blob/main/release/chrome.zip

it works on Chrome Version 110.0.5481.177 (x86_64) in macos. Thanks

**Comment by anaclumos** [comment]
Submitted on the store for review. Will be live in couple hours!

**Comment by anaclumos** [comment]
Honestly it's hilarious what happened 😭

Turns out, Bing added a proprietary header that's only used in Bing.com. It's called `UserAgentReductionOptOut`. After faking that as well, the problem went away.

More info:

[<img src="https://og.cho.sh/api/og?title=Bing%20Chat%20Widespread%20Unavailability%20Incident%20Report%20(April%202023)&subheading=Sunghyun%20Cho" width="500" />](https://cho.sh/r/AB7939)

[Bing Chat Widespread Unavailability Incident (April 2023) @ Sunghyun Cho](https://cho.sh/r/AB7939)


Really @Microsoft ?
