### ISSUE TITLE
Scrolling in Firefox

### ISSUE THREAD

**Issue by Hossam225** [anaclumos/bing-chat-for-all-browsers#76]
Scrolling doesn't work on the latest Firefox 102.10.0esr
in the about:config, I searched for "layout.css.overflow-overlay.enabled" but it doesn't exist. I created it as Boolean and set it to true. But this didn't solve the problem.

**Comment by anaclumos** [comment]
You must use version 110+. Do you mind using the non-esr version?

**Comment by anaclumos** [comment]
Can you check if your `layout.css.overflow-overlay.enabled` is set to true?

**Comment by MBakhshi96** [comment]
it is set to true.
