### ISSUE TITLE
Extension suddenly stopped working

### ISSUE THREAD

**Issue by pllopis** [anaclumos/bing-chat-for-all-browsers#77]
I have been using this extension successfully on Chrome and MacOS for a few weeks. Today it just stopped working. I didn't update any other software components, especially not Chrome, just before it stopped working.

**Comment by youtehub** [comment]
Yes, it needs to be repaired and re-listed

**Comment by pllopis** [comment]
Yes, well, I tried in Incognito mode to get rid of any cookies/caches and get a fresh login.
If you look on the web there are multiple numerous reports in the last 24h of people experiencing the same thing.

If your session is till working, I suspect that it might be because your Bing cookie hasn't expired. Does your session still work after logging out and back in?

**Comment by pllopis** [comment]
Thanks for the heads up @andrewnjl
Sorry I had not seen that issue. However I just double checked that I'm already on v1.0.6. I again cleared all bing cookies and logged in, but I'm still getting the same issue.

**Comment by pllopis** [comment]
Weirdly, now it is working, even though I haven't really changed anything. I was trying if changing my default UA via the inspector would help, and it did. Except then I logged out, cleared cookies, switched back to Chrome's default, logged back in, and Bing was back.  Perhaps there's something on the Bing side that's being changed?

**Comment by dillontkh** [comment]
Firefox has yet to receive the fix

**Comment by anaclumos** [comment]
It's a never-ending chase between @microsoft and me 😁 let me know if the issue continues to happen.
