### ISSUE TITLE
Doesn't work on Arc browser (Chromium)

### ISSUE THREAD

**Issue by realdep** [anaclumos/bing-chat-for-all-browsers#78]
![image](https://user-images.githubusercontent.com/9782679/233163832-7eb05215-c251-4e58-885d-eb7660c8d163.png)
I cleared cache and cookies, tried reinstalling, uninstalling, Doesn't work

**Comment by anaclumos** [comment]
I'm using Arc as well.

- Do you have a MS account with Bing access?
- Can you use it with Edge browser?
- Are you on v1.0.6?

**Comment by realdep** [comment]
Yes I have an MS account with bing access.
I can use it in safari with user agent spoofing.
It is 1.0.6 right now.
I was able to use it until a couple days ago and it just broke. I tried a combination of  reinstalling multiple times, spoofing the user agent in chromium, clearing cache&cookies. So far, nothing.

**Comment by realdep** [comment]
Ok it appears that ublock caused this, I didn't whitelist bing..
sorry for the time waste.
