### ISSUE TITLE
Can't install the latest version from release page

### ISSUE THREAD

**Issue by VictoriousRaptor** [anaclumos/bing-chat-for-all-browsers#81]
When I try to install it Firefox says it's broken. I'm running 112.0.1 64-bit.

**Comment by anaclumos** [comment]
Is it v1.0.7? I can install it on my side.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/31657298/233449837-3a7ea8d1-68a8-48c7-bf8a-4d047ae52e8f.png">

**Comment by ReneMalenfant** [comment]
I can't install it on Firefox either. It installs as a temporary extension if you do it through "Debug Add-ons" (as shown in the screenshot), but if you try to install it as a regular add-on using "Install add-on from file", then it fails and says it's corrupt.

The temporary extension works fine on the Bing website, but as soon as you restart your browser, it's gone.

**Comment by anaclumos** [comment]
Hmm, I do not have any expertise on this; I don't think the changes made for v1.0.7 suddenly made the code corrupted. Does it seem like there are some signatures missing? Does anyone know the recommended steps to resolve this?
