### ISSUE TITLE
Plugin does not work on Windows 10, latest Chrome browser

### ISSUE THREAD

**Issue by crazydude123** [anaclumos/bing-chat-for-all-browsers#82]
1.0.7 works fine on an Ubuntu Chrome browser but does not seem to work on a Windows 10 Chrome browser.
I don't know what the source of this problem could be :/

**Comment by anaclumos** [comment]
By "Not Working", do you mean you cannot access Bing Chat?

**Comment by anaclumos** [comment]
+ please confirm you have tried clearing the cookies and cache, and logging off and on.

**Comment by crazydude123** [comment]
Yes, the chat button opens the "install edge" popup

**Comment by anaclumos** [comment]
Please kindly confirm if you cleared cache and cookies, and logging back in.

**Comment by cheparity** [comment]
I come across the same question. Although I clear all cookies, it still doesn't work. The same question occurs at other plugins such as 'bing unchained'.
Besides, a strange phenomenon is that when I click login button in new bing, it is automatically login without inputting password. I guess chrome in newest version  maybe has some strange relationship with Windows...?

**Comment by cheparity** [comment]
> @cheparity The extension is working for the latest version of Chrome (Version 112.0.5615.138), if you cleared your cookies and already tried to relogin on Bing a) Make sure your Chrome settings do not block all cookies under "Cookies and other site data" b) Turn off all your extensions (some extensions such as adblockers or privacy related tools may be interfering)
> 
> Turn on only this plugin (aka Bing Chat for all Browser) and it should work as intended already. Once you can access Bing Chat you can proceed to turn on all your extensions.

Sorry for late response. It works now. Thank you for maintaining this plugin.
