### ISSUE TITLE
Feature request: Bing chat results on bing searches 

### ISSUE THREAD

**Issue by 4nur4g** [anaclumos/bing-chat-for-all-browsers#84]
It'll be great if this extension enables Bing chat results on the same Bing search page like seen on Edge, where Bing chat results are shown on the right side of search results. 

Something like this:

![image](https://user-images.githubusercontent.com/33851499/233832569-db321248-5d57-44f2-a8c1-550ba162ea2c.png)

**Comment by anaclumos** [comment]
That's a great idea! Is this exclusive to Edge? I have seen this couple of times, but right now I am trying to see if there's a way to trick Bing to do this, where I cannot replicate this on both Edge and Chrome. Do you know if there's any conditions to activate this?
