### ISSUE TITLE
on start it explains what bing ai is

### ISSUE THREAD

**Issue by xXVince26Xx** [anaclumos/bing-chat-for-all-browsers#89]
When i start up the bing ai it starts to explain what bing ai is. Please fix it, it's really annoying.

**Comment by stephane303** [comment]
I confirm, it appeared today

**Comment by anaclumos** [comment]
Hi, the do you mean by clicking the "Open Bing Chat" button? It is currently set to `bing.com/chat`.

**Comment by stephane303** [comment]
the issue is gone today
