### ISSUE TITLE
No longer recognises that you are signed in

### ISSUE THREAD

**Issue by Boreo** [anaclumos/bing-chat-for-all-browsers#90]
Not sure if this was an issue before as I didn't notice it, but it no longer allows more than 5 chats as it recognises you as logged out, even if you're logged in.

Browser: Firefox 112.0.2

![image](https://user-images.githubusercontent.com/7530279/235367837-6e7de37e-cb5e-4744-a8db-1c7962df2eb8.png)

**Comment by koujiangheng** [comment]
same problem at google chrome Version 113.0.5672.63 (Official Build) (64-bit)

**Comment by PixelQubed** [comment]
Same problem. The latest build of Chrome at this moment in time.
Version 113.0.5672.127 (Official Build) (64-bit)

**Comment by 7k50** [comment]
I just installed this plugin and I seem to have this problem. I have tried clearing the Bing cookies as the instruction says. I am logged into my Microsoft account however. 

Does anyone else have the issue currently and can confirm?

**Comment by ITESaurabh** [comment]
similar for  me

![image](https://github.com/anaclumos/bing-chat-for-all-browsers/assets/50075159/f1d50598-9a8a-4aa3-9880-749bb7fbaa3b)

Does not login at all.

Firefox 114.0.1 Stable on Windows 11

**Comment by anaclumos** [comment]
#119
