### ISSUE TITLE
Spacebar acting as page down instead of space. 

### ISSUE THREAD

**Issue by Dotherecy** [anaclumos/bing-chat-for-all-browsers#91]
In every browser I use this extension on, I cannot use the spacebar. Even the official bing search website. The extension continues this issue. It seems like when the page is loading up either in the extension or otherwise, **focus** has it's priority set to default as the page instead of the chatbox- no amount of clicking changes that. Chrome, Brave, Opera, Vivali, Edge- every one.

**Comment by anaclumos** [comment]
<img width="601" alt="Screenshot 2023-05-01 at 9 03 13 PM" src="https://user-images.githubusercontent.com/31657298/235576829-7d0a6d30-e3be-484e-890a-b50a7c3bf866.png">

<img width="274" alt="image" src="https://user-images.githubusercontent.com/31657298/235576955-f3cb16aa-4e30-4442-94a1-d3f311a961fe.png">


Do you mean you cannot use the space bar? I can use the space bar, as shown in the image.
