### ISSUE TITLE
Extension doesnt seem to be able to bypass Microsofts restriction? 

### ISSUE THREAD

**Issue by Cedar3702** [anaclumos/bing-chat-for-all-browsers#92]
![image](https://user-images.githubusercontent.com/122573966/236060342-72334e8d-3246-46fd-843a-b819a1f16534.png)

**Comment by anaclumos** [comment]
What happens when you press start chatting?

**Comment by Cedar3702** [comment]
I'm so sorry I am not sure what I was thinking. Yeah, it works! Must have been tired when writing that lol
