### ISSUE TITLE
Extension Redirected and not running on chrome

### ISSUE THREAD

**Issue by Jotz-X** [anaclumos/bing-chat-for-all-browsers#97]
easier to record than to explain so here:
https://streamable.com/tp139a
Idk why the extension pop up wasn't captured, but its beyond me 

PS : Lmk if video link expires ill renew it

**Comment by anaclumos** [comment]
What happens when you click on "Chat" on your menu bar?

**Comment by Jotz-X** [comment]
it just sends me to a search query on google
https://www.google.com/search?q=Bing+AI

**Comment by anaclumos** [comment]
That is super strange. It should at least search "Bing AI" on Bing, not Chrome. It seems like some other extension is routing Bing search requests to Google. Do you mind checking other extensions that you have?
