### ISSUE TITLE
Can't show line break properly in firefox

### ISSUE THREAD

**Issue by thd2020** [anaclumos/bing-chat-for-all-browsers#98]
Hello dear anaclumos, I've found a small problem in firefox. In brief, when you type in shift+return, there could not appear a "visible" start of a new line but just like input a blankspace. And also in developer tools I found no EOL like "\n". It seems that the problem was brought out three weaks ago and persisting.

**Comment by rootedetc** [comment]
This is a duplicate issue of #16 .

**Comment by thd2020** [comment]
@rootedetc Oh yes, I hadn't check it. However the issue seems to remain unsolved.

**Comment by anaclumos** [comment]
Let's track it over #16.
