### ISSUE TITLE
Always prompt to log in 

### ISSUE THREAD

**Issue by Sheldontao** [anaclumos/bing-chat-for-all-browsers#99]
I can enter Bingchat, but I can't log in 
<img width="1110" alt="image" src="https://github.com/anaclumos/bing-chat-for-all-browsers/assets/36765652/e98a1b9e-0aba-4514-be26-d1dd21dc943d">

**Comment by SNWCreations** [comment]
try to create a new ms account? I met this before. and i created a new ms account, it works.

**Comment by anaclumos** [comment]
#119
